In [20]:
import numpy as np
import pandas as pd

In [21]:
df = pd.read_csv("Customer_Analysis.csv")

In [22]:
data = df.select_dtypes(include=np.number).values

In [23]:
np.shape(data)

(2240, 26)

In [24]:
np.ndim(data)

2

In [25]:
np.size(data)

58240

In [26]:
np.dtype(data.dtype)

dtype('float64')

In [27]:
np.mean(data, axis=0)

array([5.59215982e+03, 1.96880580e+03,            nan, 4.44196429e-01,
       5.06250000e-01, 4.91093750e+01, 3.03935714e+02, 2.63022321e+01,
       1.66950000e+02, 3.75254464e+01, 2.70629464e+01, 4.40218750e+01,
       2.32500000e+00, 4.08482143e+00, 2.66205357e+00, 5.79017857e+00,
       5.31651786e+00, 7.27678571e-02, 7.45535714e-02, 7.27678571e-02,
       6.42857143e-02, 1.33928571e-02, 9.37500000e-03, 3.00000000e+00,
       1.10000000e+01, 1.49107143e-01])

In [28]:
np.median(data, axis=0)

array([5.4585e+03, 1.9700e+03,        nan, 0.0000e+00, 0.0000e+00,
       4.9000e+01, 1.7350e+02, 8.0000e+00, 6.7000e+01, 1.2000e+01,
       8.0000e+00, 2.4000e+01, 2.0000e+00, 4.0000e+00, 2.0000e+00,
       5.0000e+00, 6.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 3.0000e+00, 1.1000e+01,
       0.0000e+00])

In [30]:
np.std(data, axis=0)

array([3.24593742e+03, 1.19813941e+01,            nan, 5.38277906e-01,
       5.44416668e-01, 2.89559873e+01, 3.36522251e+02, 3.97645548e+01,
       2.25664984e+02, 5.46167841e+01, 4.12712831e+01, 5.21557931e+01,
       1.93180615e+00, 2.77809383e+00, 2.92244810e+00, 3.25023240e+00,
       2.42610329e+00, 2.59755069e-01, 2.62669634e-01, 2.59755069e-01,
       2.45261210e-01, 1.14949939e-01, 9.63696497e-02, 0.00000000e+00,
       0.00000000e+00, 3.56194052e-01])

In [31]:
np.var(data, axis=0)

array([1.05361097e+07, 1.43553806e+02,            nan, 2.89743104e-01,
       2.96389509e-01, 8.38449198e+02, 1.13247225e+05, 1.58121982e+03,
       5.09246850e+04, 2.98299310e+03, 1.70331881e+03, 2.72022675e+03,
       3.73187500e+00, 7.71780533e+00, 8.54070293e+00, 1.05640107e+01,
       5.88597716e+00, 6.74726961e-02, 6.89953364e-02, 6.74726961e-02,
       6.01530612e-02, 1.32134885e-02, 9.28710937e-03, 0.00000000e+00,
       0.00000000e+00, 1.26874203e-01])

In [32]:
np.min(data, axis=0)

array([   0., 1893.,   nan,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    3.,   11.,    0.])

In [33]:
np.max(data, axis=0)

array([1.1191e+04, 1.9960e+03,        nan, 2.0000e+00, 2.0000e+00,
       9.9000e+01, 1.4930e+03, 1.9900e+02, 1.7250e+03, 2.5900e+02,
       2.6300e+02, 3.6200e+02, 1.5000e+01, 2.7000e+01, 2.8000e+01,
       1.3000e+01, 2.0000e+01, 1.0000e+00, 1.0000e+00, 1.0000e+00,
       1.0000e+00, 1.0000e+00, 1.0000e+00, 3.0000e+00, 1.1000e+01,
       1.0000e+00])

In [34]:
np.sum(data, axis=0)

array([1.2526438e+07, 4.4101250e+06,           nan, 9.9500000e+02,
       1.1340000e+03, 1.1000500e+05, 6.8081600e+05, 5.8917000e+04,
       3.7396800e+05, 8.4057000e+04, 6.0621000e+04, 9.8609000e+04,
       5.2080000e+03, 9.1500000e+03, 5.9630000e+03, 1.2970000e+04,
       1.1909000e+04, 1.6300000e+02, 1.6700000e+02, 1.6300000e+02,
       1.4400000e+02, 3.0000000e+01, 2.1000000e+01, 6.7200000e+03,
       2.4640000e+04, 3.3400000e+02])

In [35]:
np.percentile(data, 25, axis=0)

array([2.82825e+03, 1.95900e+03,         nan, 0.00000e+00, 0.00000e+00,
       2.40000e+01, 2.37500e+01, 1.00000e+00, 1.60000e+01, 3.00000e+00,
       1.00000e+00, 9.00000e+00, 1.00000e+00, 2.00000e+00, 0.00000e+00,
       3.00000e+00, 3.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 3.00000e+00, 1.10000e+01,
       0.00000e+00])

In [36]:
np.percentile(data, 50, axis=0)

array([5.4585e+03, 1.9700e+03,        nan, 0.0000e+00, 0.0000e+00,
       4.9000e+01, 1.7350e+02, 8.0000e+00, 6.7000e+01, 1.2000e+01,
       8.0000e+00, 2.4000e+01, 2.0000e+00, 4.0000e+00, 2.0000e+00,
       5.0000e+00, 6.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 3.0000e+00, 1.1000e+01,
       0.0000e+00])

In [37]:
np.percentile(data, 75, axis=0)

array([8.42775e+03, 1.97700e+03,         nan, 1.00000e+00, 1.00000e+00,
       7.40000e+01, 5.04250e+02, 3.30000e+01, 2.32000e+02, 5.00000e+01,
       3.30000e+01, 5.60000e+01, 3.00000e+00, 6.00000e+00, 4.00000e+00,
       8.00000e+00, 7.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 3.00000e+00, 1.10000e+01,
       0.00000e+00])

In [38]:
np.isnan(data)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]], shape=(2240, 26))

In [39]:
np.nanmean(data)

np.float64(2306.2933901332967)

In [40]:
np.nanmedian(data)

np.float64(3.0)

In [41]:
income = df["Income"].values

In [42]:
np.mean(income)

np.float64(nan)

In [43]:
np.median(income)

np.float64(nan)

In [44]:
np.std(income)

np.float64(nan)

In [45]:
np.where(income < 50000)

(array([   1,    3,    7, ..., 2231, 2232, 2234], shape=(1060,)),)

In [46]:
data[income > 50000]

array([[5.5240e+03, 1.9570e+03, 5.8138e+04, ..., 3.0000e+00, 1.1000e+01,
        1.0000e+00],
       [4.1410e+03, 1.9650e+03, 7.1613e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       [5.3240e+03, 1.9810e+03, 5.8293e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       ...,
       [7.2700e+03, 1.9810e+03, 5.6981e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       [8.2350e+03, 1.9560e+03, 6.9245e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       [9.4050e+03, 1.9540e+03, 5.2869e+04, ..., 3.0000e+00, 1.1000e+01,
        1.0000e+00]], shape=(1156, 26))

In [47]:
np.sort(income)

array([1730., 2447., 3502., ...,   nan,   nan,   nan], shape=(2240,))

In [48]:
np.sort(income)[::1]

array([1730., 2447., 3502., ...,   nan,   nan,   nan], shape=(2240,))

In [49]:
np.unique(df["Education"].values, return_counts=True)

(array(['2n Cycle', 'Basic', 'Graduation', 'Master', 'PhD'], dtype=object),
 array([ 203,   54, 1127,  370,  486]))

In [50]:
np.sqrt(income)

array([241.11822826, 215.2765663 , 267.60605374, ..., 238.70693329,
       263.14444702, 229.93259882], shape=(2240,))

In [51]:
np.log(income)

array([10.97057477, 10.74384711, 11.1790319 , ..., 10.95047316,
       11.14540622, 10.87557243], shape=(2240,))

In [52]:
np.exp(income)

/var/folders/0c/7f8p6mvs5mg8nbh9mllqtkb80000gn/T/ipykernel_1262/2986110126.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(income)


array([inf, inf, inf, ..., inf, inf, inf], shape=(2240,))

In [54]:
np.corrcoef(data.T)

/opt/anaconda3/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3065: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/opt/anaconda3/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3066: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


array([[ 1.00000000e+00,  2.76244970e-05,             nan,
         2.40560645e-03, -2.57989085e-03, -4.65241020e-02,
        -2.28782897e-02,  4.60006215e-03, -4.43721758e-03,
        -2.44749481e-02, -7.64155690e-03, -1.34378327e-02,
        -3.71658482e-02, -1.89238966e-02, -3.44014349e-03,
        -1.49269287e-02, -7.44618234e-03, -3.60399967e-02,
        -2.53867202e-02, -7.51702417e-03, -2.16142374e-02,
        -1.50609631e-02,  3.38830381e-02,             nan,
                    nan, -2.19678176e-02],
       [ 2.76244970e-05,  1.00000000e+00,             nan,
         2.30175538e-01, -3.52111433e-01, -1.98710887e-02,
        -1.57772523e-01, -1.79172403e-02, -3.08723991e-02,
        -4.16253774e-02, -1.81326066e-02, -6.18181817e-02,
        -6.08455503e-02, -1.45040138e-01, -1.21274632e-01,
        -1.28272056e-01,  1.21139259e-01,  6.17744799e-02,
        -6.05095954e-02,  7.12254154e-03, -5.93031675e-03,
        -6.53928407e-03, -3.01275448e-02,             nan,
             

In [55]:
np.hstack([data, data])

array([[5.5240e+03, 1.9570e+03, 5.8138e+04, ..., 3.0000e+00, 1.1000e+01,
        1.0000e+00],
       [2.1740e+03, 1.9540e+03, 4.6344e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       [4.1410e+03, 1.9650e+03, 7.1613e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       ...,
       [7.2700e+03, 1.9810e+03, 5.6981e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       [8.2350e+03, 1.9560e+03, 6.9245e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       [9.4050e+03, 1.9540e+03, 5.2869e+04, ..., 3.0000e+00, 1.1000e+01,
        1.0000e+00]], shape=(2240, 52))

In [56]:
np.vstack([data, data])

array([[5.5240e+03, 1.9570e+03, 5.8138e+04, ..., 3.0000e+00, 1.1000e+01,
        1.0000e+00],
       [2.1740e+03, 1.9540e+03, 4.6344e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       [4.1410e+03, 1.9650e+03, 7.1613e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       ...,
       [7.2700e+03, 1.9810e+03, 5.6981e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       [8.2350e+03, 1.9560e+03, 6.9245e+04, ..., 3.0000e+00, 1.1000e+01,
        0.0000e+00],
       [9.4050e+03, 1.9540e+03, 5.2869e+04, ..., 3.0000e+00, 1.1000e+01,
        1.0000e+00]], shape=(4480, 26))